# Generated by Django 3.1.4 on 2021-01-26 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariomodel',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comentariomodel',
            name='archivo',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comentariomodel',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comentariomodel',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
