# Generated by Django 3.1.4 on 2020-12-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('C', 'Condominio'), ('A', 'administrador'), ('E', 'Empleado')], max_length=10),
        ),
    ]
