# Generated by Django 3.1.4 on 2020-12-16 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominio', '0002_auto_20201214_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('fecha', models.DateField()),
                ('id_usuario', models.IntegerField()),
                ('id_apartamento', models.IntegerField()),
                ('nombre_propietario', models.TextField()),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.condominio')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
