# Generated by Django 3.1.4 on 2021-01-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='numero_factura',
            field=models.TextField(default='0'),
        ),
    ]
