# Generated by Django 3.1.4 on 2021-01-27 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_pago_numero_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
