# Generated by Django 3.1.4 on 2020-12-29 14:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(default='', max_length=20)),
                ('contenido', models.TextField(default='', max_length=40)),
                ('fecha_vencimiento', models.DateField(default=datetime.date.today)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('id_apartamento', models.IntegerField(default='')),
                ('file', models.FileField(default='', max_length=1000, upload_to='uploads')),
                ('id_asignado', models.ForeignKey(default='', limit_choices_to={'tipo': 'E'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_condominio', models.ForeignKey(default='', limit_choices_to={'tipo': 'C'}, on_delete=django.db.models.deletion.CASCADE, related_name='condominio_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'tareas',
            },
        ),
    ]
