# Generated by Django 3.1.4 on 2020-12-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0005_auto_20201216_2337'),
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientomodel',
            name='prueba',
            field=models.ManyToManyField(default='', to='condominio.Condominio'),
        ),
    ]
