# Generated by Django 3.1.4 on 2020-12-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0005_auto_20201216_2337'),
        ('seguimiento', '0002_seguimientomodel_prueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientomodel',
            name='prueba',
            field=models.ManyToManyField(db_table='id_apartamento', default='', to='condominio.Condominio'),
        ),
    ]
