# Generated by Django 3.1.4 on 2021-01-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0003_auto_20201229_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientomodel',
            name='file',
            field=models.FileField(blank=True, default='', max_length=1000, upload_to='uploads'),
        ),
    ]
