# Generated by Django 3.1.4 on 2021-01-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0004_auto_20210110_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientomodel',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
