# Generated by Django 3.1.4 on 2021-01-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0007_auto_20210118_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimientomodel',
            name='prueba',
        ),
        migrations.AlterField(
            model_name='seguimientomodel',
            name='id_apartamento',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='seguimientomodel',
            name='titulo',
            field=models.CharField(default='', max_length=20),
        ),
    ]
