# Generated by Django 3.1.4 on 2020-12-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('propietario', models.TextField()),
                ('torre', models.TextField(max_length=4)),
                ('apartamento', models.TextField(max_length=4)),
                ('total_mes', models.TextField()),
            ],
            options={
                'verbose_name': 'Condominio',
                'verbose_name_plural': 'Condominios',
            },
        ),
    ]
