# Generated by Django 3.1.4 on 2020-12-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0003_auto_20201216_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='total_mes_log',
            field=models.TextField(default=models.TextField()),
        ),
    ]
