# Generated by Django 3.1.4 on 2020-12-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0004_condominio_total_mes_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='total_mes_log',
            field=models.TextField(default=''),
        ),
    ]
